import type { Property } from '@/types'

export const PROPERTIES: Property[] = [
  {
    id: 1,
    title: 'Luxury Beachfront Villa with Private Pool',
    type: 'Villa',
    badge: 'Beachfront',
    badgeColor: 'gold',
    price: '₹4.8 Cr',
    location: 'Candolim, North Goa',
    beds: 4,
    baths: 4,
    area: '4200 sq.ft',
    listing: 'sale',
    region: 'north',
    sellerType: 'Verified Builder',
    img: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=700&q=80',
    featured: true,
  },
  {
    id: 2,
    title: 'Premium Portuguese Style Heritage Home',
    type: 'Villa',
    badge: 'Heritage',
    badgeColor: 'navy',
    price: '₹3.2 Cr',
    location: 'Assagao, North Goa',
    beds: 3,
    baths: 3,
    area: '2800 sq.ft',
    listing: 'sale',
    region: 'north',
    sellerType: 'Owner',
    img: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=700&q=80',
    featured: true,
  },
  {
    id: 3,
    title: 'Modern Sea View Apartment',
    type: 'Apartment',
    badge: 'Sea View',
    price: '₹1.8 Cr',
    location: 'Dona Paula, Goa',
    beds: 3,
    baths: 2,
    area: '1900 sq.ft',
    listing: 'sale',
    region: 'north',
    sellerType: 'Verified Agent',
    img: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=700&q=80',
    featured: true,
  },
  {
    id: 4,
    title: 'Luxury Villa Near Baga Beach',
    type: 'Villa',
    badge: 'Prime Location',
    badgeColor: 'gold',
    price: '₹5.5 Cr',
    location: 'Baga, North Goa',
    beds: 5,
    baths: 5,
    area: '5000 sq.ft',
    listing: 'sale',
    region: 'north',
    sellerType: 'Builder',
    img: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=700&q=80',
    featured: true,
  },
  {
    id: 5,
    title: 'Residential Plot Near Beach',
    type: 'Plot',
    badge: 'Investment',
    price: '₹95 Lakhs',
    location: 'Morjim, North Goa',
    beds: null,
    baths: null,
    area: '2400 sq.ft',
    listing: 'sale',
    region: 'north',
    sellerType: 'Agent',
    img: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=700&q=80',
    featured: true,
  },
  {
    id: 6,
    title: 'Boutique Resort Investment Property',
    type: 'Commercial',
    badge: 'High Returns',
    badgeColor: 'gold',
    price: '₹6.2 Cr',
    location: 'Anjuna, Goa',
    beds: null,
    baths: null,
    area: '6500 sq.ft',
    listing: 'sale',
    region: 'north',
    sellerType: 'Developer',
    img: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=700&q=80',
    featured: true,
  },
  {
    id: 7,
    title: '2BHK Apartment in Bambolim',
    type: 'Apartment',
    badge: 'Hot',
    badgeColor: 'gold',
    price: '₹2.32 Cr',
    location: 'Bambolim, North Goa',
    beds: 2,
    baths: 2,
    area: '1550 sq.ft',
    listing: 'sale',
    region: 'north',
    sellerType: 'Agent',
    img: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=700&q=80',
  },
  {
    id: 8,
    title: '3BHK Villa for Rent in Siolim',
    type: 'Villa',
    badge: '',
    price: '₹55,000',
    priceNote: '/month',
    location: 'Siolim, North Goa',
    beds: 3,
    baths: 3,
    area: '2800 sq.ft',
    listing: 'rent',
    region: 'north',
    sellerType: 'Owner',
    img: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=700&q=80',
  },
  {
    id: 9,
    title: 'Furnished Apartment in Panjim',
    type: 'Apartment',
    badge: '',
    price: '₹22,000',
    priceNote: '/month',
    location: 'Panjim, Goa',
    beds: 2,
    baths: 2,
    area: '1100 sq.ft',
    listing: 'rent',
    region: 'north',
    sellerType: 'Owner',
    img: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=700&q=80',
  },
  {
    id: 10,
    title: 'Plot for Sale in Porvorim',
    type: 'Plot',
    badge: '',
    price: '₹1.1 Cr',
    location: 'Porvorim, North Goa',
    beds: null,
    baths: null,
    area: '3200 sq.ft',
    listing: 'sale',
    region: 'north',
    sellerType: 'Agent',
    img: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=700&q=80',
  },
]

export const LOCATIONS = [
  'All Goa', 'Anjuna', 'Arpora', 'Ashwem', 'Assagao', 'Baga', 'Bambolim',
  'Calangute', 'Candolim', 'Chapora', 'Colva', 'Dona Paula', 'Mandrem',
  'Mapusa', 'Margao', 'Morjim', 'Panjim', 'Porvorim', 'Siolim',
  'Vagator', 'Vasco', 'Aldona', 'Benaulim', 'Betalbatim', 'Cavelossim',
  'Bogmalo', 'Curchorem', 'Palolem', 'Agonda',
]

export const PROPERTY_TYPES = [
  { label: 'All Types', value: '' },
  { label: 'Apartments & Penthouses', value: 'apartments' },
  { label: 'Bungalows & Villas', value: 'villas' },
  { label: 'Portuguese Houses', value: 'portuguese' },
  { label: 'Plots', value: 'plots' },
  { label: 'Boutique Resort', value: 'resort' },
  { label: 'Beach / River Side Properties', value: 'beach' },
  { label: 'Agriculture / Farm Land', value: 'farm' },
  { label: 'Row House & Duplex', value: 'rowhouse' },
  { label: 'Industrial Sheds / Plots', value: 'industrial' },
  { label: 'Commercial', value: 'commercial' },
]

export const BUDGET_OPTIONS = [
  { label: 'Any Budget', value: '' },
  { label: 'Under ₹50 Lakhs', value: '0-50' },
  { label: '₹50L – ₹1 Cr', value: '50-100' },
  { label: '₹1 Cr – ₹2 Cr', value: '100-200' },
  { label: '₹2 Cr – ₹5 Cr', value: '200-500' },
  { label: 'Above ₹5 Cr', value: '500+' },
]

export const RENT_BUDGET_OPTIONS = [
  { label: 'Any Budget', value: '' },
  { label: 'Under ₹10k/mo', value: '0-10' },
  { label: '₹10k – ₹25k/mo', value: '10-25' },
  { label: '₹25k – ₹50k/mo', value: '25-50' },
  { label: '₹50k – ₹1L/mo', value: '50-100' },
  { label: 'Above ₹1L/mo', value: '100+' },
]

export const GOA_PLACES = [
  // North Goa areas
  'Anjuna', 'Arambol', 'Arpora', 'Ashwem', 'Assagao', 'Baga', 'Bambolim', 'Bicholim',
  'Calangute', 'Candolim', 'Caranzalem', 'Chapora', 'Chicalim', 'Dona Paula',
  'Fontainhas', 'Mandrem', 'Mapusa', 'Miramar', 'Moira', 'Morjim',
  'Nachinola', 'Nerul', 'Old Goa', 'Panjim', 'Panaji', 'Pernem',
  'Pilerne', 'Ponda', 'Porvorim', 'Reis Magos', 'Ribandar',
  'Saligao', 'Sangolda', 'Siolim', 'Sinquerim', 'Socorro', 'Tivim', 'Vagator',
  // South Goa areas
  'Agonda', 'Benaulim', 'Betalbatim', 'Bogmalo', 'Canacona', 'Cavelossim',
  'Colva', 'Cortalim', 'Curchorem', 'Dabolim', 'Goa Velha', 'Loutolim',
  'Majorda', 'Margao', 'Nuvem', 'Palolem', 'Quepem',
  'Sanguem', 'Utorda', 'Vasco', 'Verna',
  // Regions
  'North Goa', 'South Goa', 'All Goa',
  // Beaches
  'Agonda Beach', 'Anjuna Beach', 'Arambol Beach', 'Ashwem Beach',
  'Baga Beach', 'Benaulim Beach', 'Bogmalo Beach', 'Calangute Beach',
  'Candolim Beach', 'Cavelossim Beach', 'Colva Beach', 'Dona Paula Beach',
  'Mandrem Beach', 'Miramar Beach', 'Morjim Beach', 'Palolem Beach',
  'Sinquerim Beach', 'Vagator Beach',
  // Notable localities
  'Aldona', 'Altinho', 'Cansaulim', 'Corjuem', 'Mapusa Market',
  'Panjim City', 'Raia', 'Soccoro',
]

export const FEATURED_PROPERTIES = PROPERTIES.filter((p) => p.featured)
export const SALE_PROPERTIES = PROPERTIES.filter((p) => p.listing === 'sale')
export const RENT_PROPERTIES = PROPERTIES.filter((p) => p.listing === 'rent')
